%% One change point
clear;clc;
N       =   [1100, 900];
nr      =   50;
nc      =   50;
r       =   5;
s       =   2;

noise     = struct(...
    'type',  'Gaussian',...
    'scale', 1.0,...
    'para',  0.5);
design    = struct(...
    'type',  'CS',...
    'dist',  'Gaussian',...
    'scale', 1.0,...
    'para',  1.0);

data_opts = struct(...
    'nr', nr,...
    'nc', nc,...
    'N' , N,...
    'r' , r,...
    's' , s,...
    'noise',  noise,...
    'design', design);


screen_opts = struct(...
    'nr', nr,...
    'nc', nc,...
    'N' , N ,...
    'inc', 20,...
    'method', 'B',...
    'comb_flag', 'cauchy');

startInd = 200;
endInd   = 1800;

[p_value, ~, ~, outInfo] = runTrial(startInd, endInd, data_opts, screen_opts);

plot(outInfo.result.p_value_original);



%% Zero change point
clear;clc;
N       =   3000;
nr      =   40;
nc      =   40;
r       =   5;
s       =   1;
Theta_star = zeros(nr, nc, s);

for k = 1:s
    [U,~,~]     =  svd(normrnd(0,1,[nr, 100]), 'econ');
    [V,~,~]     =  svd(normrnd(0,1,[nc, 100]), 'econ');
    Theta_star(:,:,k)  =  U(:, 1:r) * V(:, 1:r)' / sqrt(r);
end

noise     = struct(...
    'type',  'Gaussian',...
    'scale', 1.0,...
    'para',  0.25);
design    = struct(...
    'type',  'CS',...
    'dist',  'Gaussian',...
    'scale', 1.0,...
    'para',  1.0);

data_opts = struct(...
    'nr', nr,...
    'nc', nc,...
    'N' , N,...
    'r' , r,...
    's' , s,...
    'noise',  noise,...
    'design', design, ...
    'mech', 'given', ...
    'Theta_star', Theta_star);

screen_opts = struct(...
    'nr', nr,...
    'nc', nc,...
    'N' , N ,...
    'inc', 1,...
    'method', 'B',...
    'comb_flag', 'cauchy');

startInd = 1500;
endInd   = 1500;

for tt = 1:200
    [y, X, outInfo_data]  =  DataGen_ChangePoints(data_opts);
    [p_value, outInfo_result] = preScreen_M(y, X, startInd, endInd, screen_opts);
    record(tt) = p_value;
end

plot(record);

%% Combine p values








%% 
clear;clc;
for tt = 1:100
X  =  normrnd(0, 1, [40, 40, 3000]);
y  =  ones(3000, 1);
screen_opts = struct(...
    'nr', 40,...
    'nc', 40,...
    'N' , 3e3 ,...
    'inc', 10,...
    'method', 'B',...
    'comb_flag', 'cauchy');

startInd = 600;
endInd   = 600;

[p_value, outInfo_result] = preScreen_M(y, X, startInd, endInd, screen_opts);

%plot(outInfo_result.test_pos, outInfo_result.p_value_original);
record(tt) = p_value;
end

histogram(record);


%%
clear;clc;
record = zeros(100,1);
figure;
for loc = 1:6
    for tt = 1:100
        X  =  normrnd(0, 1, [40, 40, 3000]);
        y  =  ones(3000, 1);
        screen_opts = struct(...
            'nr', 40,...
            'nc', 40,...
            'N' , 3e3 ,...
            'inc', 10,...
            'method', 'B',...
            'comb_flag', 'cauchy');
        
        startInd = 400 * loc;
        endInd   = 400 * loc;
        
        [p_value, outInfo_result] = preScreen_M(y, X, startInd, endInd, screen_opts);
        
        %plot(outInfo_result.test_pos, outInfo_result.p_value_original);
        record(tt) = p_value;
        
        subplot(2,3,loc);
        histogram(record);
        title(['Location = ', num2str(loc*400)]);
    end
end



